### ISSUE TITLE
Server, Forums, Map all offline

### ISSUE THREAD

**Issue by M4x1nator** [Strad/TheSquareMiner#13]
The server was getting some lag before a restart, restart happened, and the server hasn't been online since. I think the forums and map were down before the restart, but I'm not sure. But they're also down now regardless.

Edit:Forums online just really slow
P.S, how do you add labels to an issue?

**Comment by Strad** [comment]
Server stuck in the midst of a restart, I've resolved this.
[The webhost is under a DDoS attack](http://status.hostexcellence.com/2014/09/27/dns-name-servers-under-ddos-attack-7/).
Click "labels" on the side. If you can't it's probably because you need to be a project admin.
