### ISSUE TITLE
Forum is down

### ISSUE THREAD

**Issue by Hypolydian** [Strad/TheSquareMiner#14]
www.thesquareminer/forum
produces a general error. 
![tsm down](https://cloud.githubusercontent.com/assets/7989859/4468976/a46e9cf0-4908-11e4-8025-4c72e8350014.PNG)

**Comment by Strad** [comment]
looking into it

**Comment by M4x1nator** [comment]
For me, (I'm on a mac) it just shows a white screen. Using Chrome.

**Comment by sigi714** [comment]
Chrome and Firefox with Adblocker / Scriptblocker will stop on a white page, you get redirected afterwards.

**Comment by Hypolydian** [comment]
Strad has got it all sorted. The forum is back up.
