### ISSUE TITLE
Forums Down

### ISSUE THREAD

**Issue by M4x1nator** [Strad/TheSquareMiner#15]
It seems the forums and dynmap are down again, or my internet is just acting funny. Server is up.

Sidenote: Where is everyone!!! Waiting for 1.8?

**Comment by Hypolydian** [comment]
I see the same issues. Additionally, I'm getting timeouts when I try to log in to the server.

**Comment by Strad** [comment]
We're using http://reddit.com/r/thesquareminer for now.
