### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Hypolydian** [Strad/TheSquareMiner#16]
Server went down for the restart, and did not come back online. Probably needs a nudge?

**Comment by boopidoop** [comment]
It's still down - Used a web thingy to check, it's not client-side. The site (Dinnerbone's one) didn't even register TSM's existence.

**Comment by sigi714** [comment]
Can't even reach the console. Needs a 'real' admin :)

edit: thesquareminer.com is unreachable. Someone got its IP to test instead? Hoster problem?

**Comment by Hypolydian** [comment]
Both thesquareminer.com and the server are back up!
