### ISSUE TITLE
Sponges work?

### ISSUE THREAD

**Issue by boopidoop** [Strad/TheSquareMiner#17]
Fatgineer and I were online, and he was showing me his sea mine, a large quarry made in the ocean. I asked how he removed the water, and he showed me, with a sponge. It was working similarly to 1.8 sponges, but wasn't soaking up the water.

After some research, turning up zilt, I asked if I could try, so he passed me the sponge. It worked for me too. So either, he has some form of devil sponge, or a mod we have on here does this. Anyone know what it is?

**Comment by Hypolydian** [comment]
It's a mod that we have! Although I'm not sure of its name (perhaps Strad or Bubby would know). It's one reason some of our previous event prizes were sponge blocks.

**Comment by boopidoop** [comment]
Ah ok, I was worried I was accidentally hacking :P
