### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by Hypolydian** [Strad/TheSquareMiner#18]
Seems to have gone down last night during a scheduled restart.

**Comment by sigi714** [comment]
Could not restart, log is spammed with
20:52:13
 CONSOLE:
[INFO] Generating new properties file
20:52:13
 CONSOLE:
WARN]: Failed to save server.properties
20:52:13
 CONSOLE:
quota exceeded
20:52:13
 CONSOLE:
Method) ~[?:1.7.0_55] 

Also server said it was running on offline mode as message. I'll better let a 'real' admin take a look at it.

**Comment by sigi714** [comment]
Now its a bit more precise:

20:51:45
 CONSOLE:
ERROR An exception occurred processing Appender File org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to RandomAccessFile logs/latest.log
20:51:45
 CONSOLE:
java.io.IOException: Disk quota exceeded
[...]
20:51:46
 CONSOLE:
java.io.IOException: Disk quota exceeded

**Comment by Strad** [comment]
Looks like we ran out of hard drive space. I deleted some old test stuff which should clear up enough space. Server is back online.
