### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by Hypolydian** [Strad/TheSquareMiner#20]
Seems the server is down along with the console. As Sigi says, it sounds like  a job for a 'real' admin :)

**Comment by Strad** [comment]
The host failed to send a bill which meant the service didn't get renewed. I poked them and I'm waiting on a response -.-

**Comment by Strad** [comment]
Okay, I think I got it back up, but it looks like the Mojang authentication servers are down so I can't test logging in. The console looks healthy though.

**Comment by Hypolydian** [comment]
Console is back up for me as well now. Thanks Strad!
