### ISSUE TITLE
Authentification Servers Down

### ISSUE THREAD

**Issue by boopidoop** [Strad/TheSquareMiner#21]
Tried to log in after what feels like years (Sorry about that!), but I get a message saying;

"Authentification servers are down. Please try again later, sorry!"

I checked other servers, and they seemed fine. This is with 1.7 and 1.8

**Comment by Hypolydian** [comment]
I've replicated this issue. http://help.mojang.com shows that the authentication servers are healthy, but logging in to TSM returns the Authentication error.

**Comment by boopidoop** [comment]
Just noticed, the server description is gone, it now says "A Minecraft Server", but the logo is still there. Weird...

**Comment by boopidoop** [comment]
Well, it seems to be back! Yay!
