### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by boopidoop** [Strad/TheSquareMiner#23]
I might just be a complete fuppin' eejit here, but how long has the 1.8 server been up? I'm guessing it's not public/ready yet, because I'm not whitelisted, but does anyone know what's up with it?

**Comment by Hypolydian** [comment]
I believe Strad has been testing various Sponge development builds which are likely not stable at the moment. http://forums.spongepowered.org is the place to go if you want the latest on that front.

**Comment by boopidoop** [comment]
I should have known :D Thanks Hypo!
