### ISSUE TITLE
Allow connection to TSM with any subdomain

### ISSUE THREAD

**Issue by Strad** [Strad/TheSquareMiner#4]
Players should be able to connect to the main server without needing 'mc.' in front of thesquareminer.com

**Comment by M4x1nator** [comment]
I didn't know that was necessary, is it? Or is just part of the normal ip and you'd have to request a change with the host.

**Comment by Strad** [comment]
I haven't done it because I haven't figured out how. I assume it's possible because Dino did it for MC^2. Also, mc.thesquareminer.com should take users to the main site, not the management console. It's just cleaner.

**Comment by Strad** [comment]
Players can now log in with thesquareminer.com or mc.thesquareminer.com. mc.thesquareminer.com now displays homepage.
