### ISSUE TITLE
Wiki needs better organization

### ISSUE THREAD

**Issue by Strad** [Strad/TheSquareMiner#7]
Many of the most important wiki articles aren't even listed on the main page.

**Comment by sigi714** [comment]
I have set up most of the articles, many are just a stub which I took from the MC²-Wiki. When we started I did finished most of the Players stuff, but the staff page was never finished, I blame reallife.

In the meantime I think I don't know all the new commands for players and staff ranks, not even all the plugins (sigi714 is outdated^^). The permissions-file would be helpful (again), whats missing is time atm.
